/* cases/case-data.jsx, structured case study content
   All content is verified from felixbenito.com source pages. */

const CASES = {

  /* ─────────────────────────────────────────────────────────────────────── */
  'audi-onboarding': {
    n: '01',
    slug: 'audi-onboarding',
    card: 'assets/audi-myaudi-maintenance-onboarding-cover.jpg', cardBg: '#2B2B2B',
    company: 'Audi · myAudi',
    year: '2025',
    title: 'Onboarding maintenance into the Audi service flow',
    subtitle: 'Lifting maintenance scheduling engagement from 11.2% to 23% across the North American myAudi app, through user research, AI-assisted prototyping and cross-functional alignment.',
    cover: '',
    meta: [
      { label: 'Role',     value: 'Product Designer (lead)' },
      { label: 'Timeline', value: 'One year' },
      { label: 'Team',     value: '8 people · me, manager, 4 devs, QA, lead architect' },
      { label: 'Method',   value: 'Agile' },
      { label: 'Markets',  value: 'USA & Canada' },
      { label: 'Tools',    value: 'Figma, FigJam, Illustrator, Photoshop, Figma Make, user testing' },
    ],
    sections: [
      { type: 'text', n: '01', title: 'Context',
        body: [
          'The Owner\u2019s Literature and Maintenance features within myAudi consolidate essential vehicle resources for North American customers.',
          'While these tools aim to save users time and money, initial research revealed significant friction in the existing service.',
          'As Product Designer, I bridged this gap by leading discovery sessions, user testing and data into high-fidelity, functional prototypes.',
        ],
      },
      { type: 'imageRow', n: '02', title: 'Problems identified in the current solution',
        bullets: [
          'The design did not look premium',
          'There was no clear CTA button',
          'Login was too complicated, two similar steps',
          'The rule to see the packages was unclear',
          'The content displayed was hard to read and understand',
        ],
        images: [
          { src: 'assets/current-solution-1024x591.png', caption: 'Audit of the current solution' },
          { src: 'assets/Group-3287.jpg',                caption: 'Problems identified in the current flow' },
        ],
      },
      { type: 'kpis', n: '03', title: 'The metric that mattered',
        body: 'The most important data point was the 11.2% Engagement Rate for the "Schedule Service" flow, and it was declining. Working with the business team, we set two key results:',
        kpis: [
          { label: 'KR1', value: '14.6% → 20%', desc: 'Maintenance schedule engagement, 6 months post-launch' },
          { label: 'KR2', value: '<1% → 5%',    desc: 'Owner\u2019s Manuals engagement, 6 months post-launch' },
        ],
        image: { src: 'assets/executive-summary-850x1024.jpg', caption: 'Executive summary', maxWidth: '70%' },
      },
      { type: 'imageRow', n: '04', title: 'User research & testing',
        body: 'We interviewed EV owners across the United States and Canada to understand how they navigate maintenance, 54 survey responses, 8 user testing sessions.',
        images: [
          { src: 'assets/5-User-research-911x1024.jpg', caption: 'User research synthesis' },
          { src: 'assets/6-User-research-1011x1024.jpg', caption: 'Insight clusters' },
          { src: 'assets/7-User-research-1024x989.jpg',  caption: 'Behavioural patterns' },
          { src: 'assets/Captura-de-Tela-2025-09-25-as-08.55.16-1024x594.jpg', caption: 'User testing, session notes' },
          { src: 'assets/Captura-de-Tela-2025-09-25-as-08.55.31-1024x590.jpg', caption: 'User testing, task flow' },
          { src: 'assets/Captura-de-Tela-2025-09-25-as-08.54.45-1024x591.jpg', caption: 'User testing, synthesis' },
        ],
      },
      { type: 'callout', kind: 'leadership', title: 'Leading the room',
        body: 'I led discovery sessions and synthesis across Data, Business, Sales and Service. The job wasn\u2019t to produce screens, it was to translate four stakeholder views into a single, prioritised roadmap the engineering team could ship.',
      },
      { type: 'callout', kind: 'leadership', noTag: true, title: 'Prioritising with a UX matrix, alongside the manager',
        body: 'I scored every improvement on a UX matrix (impact against effort) and ran it with the manager to prioritise what entered development first. The table stopped being a wishlist and became a sequenced, agreed roadmap tied to the OKRs.',
      },
      { type: 'imageRow', n: '05', title: 'Personas, decisions & improvements',
        body: 'Synthesizing research into two data-driven personas with empathy maps, then a prioritised table of improvements and a documented set of design decisions.',
        images: [
          { src: 'assets/Audi-strategy-1024x782.jpg',  caption: 'Persona 1' },
          { src: 'assets/Audi-strategy-1-1024x782.jpg', caption: 'Persona 2' },
          { src: 'assets/Group-3278-959x1024.png',     caption: 'Prioritised table of improvements' },
          { src: 'assets/Audi-strategy-4-1024x548.jpg', caption: 'Design decisions documented' },
        ],
      },
      { type: 'imageRow', n: '06', title: 'Sketches & AI refinement', cols: 2,
        body: 'I started on paper for speed, then moved into digital ideation using Figma Make to iterate rapidly on visual concepts and converge on a hi-fi direction.',
        images: [
          { src: 'assets/20250926_160146-1-1024x701.jpg', caption: 'Paper sketches' },
          { src: 'assets/20250926_160146-2-1024x701.jpg', caption: 'Layout exploration' },
          { src: 'assets/Captura-de-Tela-2025-09-26-as-15.24.45-1024x775.jpg', caption: 'Figma Make iteration' },
          { src: 'assets/Captura-de-Tela-2025-09-26-as-15.23.50-1024x718.jpg', caption: 'AI-assisted refinement' },
        ],
      },
      { type: 'callout', kind: 'ai', title: 'AI inside the design loop',
        body: 'Figma Make accelerated the path from paper to hi-fi, letting the team see and feel several visual directions before committing. The AI proposed; the team decided; I kept the brand and accessibility rails.',
      },
      { type: 'principles', n: '07', title: 'Design principles (derived from research)',
        items: [
          { k: 'Effortless Access',    v: 'Every task in ≤ 3 clicks' },
          { k: 'Premium by Default',   v: 'Visual quality matches an $80K+ vehicle' },
          { k: 'Transparent Value',    v: 'Clear ROI for every service' },
          { k: 'Respect Time',         v: 'Auto-fill, saved preferences, smart defaults' },
          { k: 'Build Trust',          v: 'Honest recommendations, no hidden costs' },
        ],
      },
      { type: 'imageRow', n: '08', title: 'Proposal, responsive & hand-off',
        body: 'High-fidelity Figma prototypes adapted to Audi\u2019s new "Alpha" design system, tested across breakpoints from in-vehicle screen to mobile and desktop. Pixel-perfect dev hand-off with annotations and notes.',
        images: [
          { src: 'assets/13-Proposal-830x1024.jpg', caption: 'Hi-fi proposal in Audi Alpha system', maxWidth: '85%' },
          { src: 'assets/14-Proposal-985x1024.jpg', caption: 'Responsive design across breakpoints' },
          { src: 'assets/image-2-1024x510.jpg',     caption: 'Hand-off, annotated screen' },
          { src: 'assets/image-3-1024x514.jpg',     caption: 'Hand-off, flow detail' },
          { src: 'assets/image-4-1024x514.jpg',     caption: 'Hand-off, final spec' },
        ],
      },
      { type: 'kpis', n: '09', title: 'Impact and outcomes',
        kpis: [
          { label: 'Maintenance scheduling engagement', value: '11.2% → 23%', desc: '+106% over baseline' },
          { label: 'Owner\u2019s manual engagement',    value: '<1% → 7.3%',   desc: '46% above the 5% goal' },
          { label: 'Service booking completion',         value: '15% → 68%',    desc: 'Completion rate' },
          { label: 'Average booking time',               value: '7:45 → 2:15',  desc: '−71% time to complete' },
          { label: 'Customer satisfaction (CSAT)',       value: '3.2 → 4.6 / 5',desc: 'Post-launch survey' },
          { label: 'Estimated annual revenue impact',    value: '$4.2M',        desc: '' },
        ],
      },
    ],
    next: 'pharosgraph',
    prev: 'sales-tech-ecosystem',
  },

  /* ─────────────────────────────────────────────────────────────────────── */
  'pharosgraph': {
    n: '02',
    slug: 'pharosgraph',
    card: 'assets/pharosgraph-cover.png', cardBg: '#0B1B33',
    company: 'PharosGraph',
    year: '2026',
    title: 'Narrative intelligence, block by block',
    subtitle: 'Joining a political intelligence platform as Design Lead: from a fragmented starting point to one design language that runs from the dashboard to the press release.',
    cover: '',
    meta: [
      { label: 'Role',     value: 'Design Lead (contractor)' },
      { label: 'Scope',    value: 'Research, branding, design system, product, website, marketing' },
      { label: 'Team',     value: 'Two founders, content lead, second designer, engineering · remote' },
      { label: 'Sector',   value: 'Political intelligence SaaS' },
      { label: 'Markets',  value: 'United States' },
      { label: 'Tools',    value: 'Figma, AI tooling, design tokens, documentation' },
    ],
    sections: [
      { type: 'text', n: '01', title: 'A strong product with no shared language',
        body: [
          'The platform turns electoral, legislative, and advertising data into intelligence that advocacy and campaign teams act on. The model was solid. The way it was designed was not.',
          'Coming in as Design Lead, I found three problems that had nothing to do with taste and everything to do with how the work was built.',
        ],
        bullets: [
          'The design system was incomplete: components were missing, there was no pattern for complementary colour, and what existed had no variables or documentation.',
          'The brand was inconsistent, with no rules holding the visual language together across surfaces.',
          'The product had grown feature by feature, so the same idea looked and behaved differently from screen to screen.',
        ],
      },
      { type: 'imageRow', cols: 2,
        images: [
          { src: 'assets/pharosgraph-system-analysis.jpg', caption: 'System & accessibility analysis', flush: true },
          { src: 'assets/pharosgraph-platform-context.jpg', caption: 'Platform context & story structure', flush: true },
        ],
      },
      { type: 'text', n: '02', title: 'Understand the domain before touching the design',
        body: [
          'I was new to US politics as a subject. Designing the interface without understanding the model behind it would have been guesswork, so I grounded myself first.',
          'I built a reference board mapping the US political system: context, definitions, elections, congressional decisions, history, and the court system. It gave every later decision a factual footing, and it became a shared reference the team could point to.',
          'Then I read the market, running a competitor analysis across Civis, PolicyNote and Cloudflare to see how comparable products frame complex data, where they earn trust, and where they leave the user to do the heavy lifting.',
        ],
      },
      { type: 'imageRow', cols: 2,
        images: [
          { src: 'assets/pharosgraph-us-political-system.jpg', caption: 'US political system reference board', flush: true },
          { src: 'assets/pharosgraph-products-overview.jpg', caption: 'Product model & pipeline', flush: true },
          { src: 'assets/pharosgraph-competitive-1.jpg', caption: 'Competitor analysis, context & strategy', flush: true },
          { src: 'assets/pharosgraph-competitive-2.jpg', caption: 'Competitor analysis, landing & dashboards', flush: true },
        ],
      },
      { type: 'callout', kind: 'leadership', noTag: true, title: 'The opportunity was not more data on screen',
        body: 'It was a single, consistent language that could carry meaning from the raw model all the way to the buyer. That insight set the order of everything that followed.',
      },
      { type: 'text', n: '03', title: 'Rebuild the system first, then let it lead',
        body: [
          'With three problems and one designer, the order of work was the real decision. I chose to fix the foundation before the surfaces.',
          'Rather than redesign the product and the website in parallel and reconcile them later, I rebuilt the design system first and let it drive both. One palette, one set of naming rules, one voice. Everything downstream inherits from it, so consistency stops being something I police and becomes something the system enforces.',
        ],
        bullets: [
          'Problem: a system missing components, colour rules, variables and documentation could not support a product, a site and a marketing library at once.',
          'Decision: fix and document the legacy components, set the pattern for new ones with variables and variants, and add the complementary colour rule the system never had.',
          'Result: a documented system that holds product and brand together, that the whole team, including our AI tooling, can build on without me in the room.',
        ],
      },
      { type: 'callout', kind: 'ai', title: 'A system legible to machines, not just people',
        body: 'I created a convention to organise projects and Figma layers so each project carries its own documentation, prioritisation and context, and named layers so AI tools can read them reliably. Then I wrote the specs and prompts that let the system run inside that tooling.',
      },
      { type: 'imageRow', cols: 2,
        images: [
          { src: 'assets/pharosgraph-color-tokens.jpg', caption: 'Brand colour tokens, style guide', flush: true },
          { src: 'assets/pharosgraph-button-components.jpg', caption: 'Component variants in Figma', flush: true },
          { src: 'assets/pharosgraph-logo-problems.jpg', caption: 'Logo redesign, problems identified', flush: true },
          { src: 'assets/pharosgraph-logo-improvements.jpg', caption: 'Logo redesign, improvements', flush: true },
          { src: 'assets/pharosgraph-doc-conventions.jpg', caption: 'Documentation conventions for AI tooling', flush: true, wide: true },
        ],
      },
      { type: 'text', n: '04', title: 'GovScape, rebuilt around one question',
        body: [
          'GovScape is a complex policy-pressure and bills tool. I anchored the redesign to the question its users ask every day: where do constituents care about this issue, how does this legislator think, and what do I do about it?',
          'With that question as the test, I audited every section, screen and component, and judged each one by whether it moved the user closer to an answer.',
        ],
        bullets: [
          'Problem: the tool had grown feature by feature: inconsistent patterns, extra steps, and screens that showed data without pointing to a next action.',
          'Decision: apply the new system across the full dashboard, then reshape the experience: organise the flow, cut steps, introduce clickable cards, vary table shapes to fit the data, and add tooltips where the model needed explaining.',
          'Result: a consistent dashboard where each screen earns its place against the user\u2019s question, with frequent engineering handoffs and production reviews to catch anything missing.',
        ],
      },
      { type: 'imageRow', cols: 2,
        images: [
          { src: 'assets/pharosgraph-govscape-sketch.jpg', caption: 'PolicyScape directory, early sketch', flush: true },
          { src: 'assets/pharosgraph-govscape-ai-prototype.jpg', caption: 'GovScape dashboard, AI low-fi prototype', flush: true },
        ],
      },
      { type: 'text',
        body: [
          'Before any pixel-perfect work, I used AI to build low-fidelity, clickable prototypes of the dashboard, exploring layouts, hierarchy and interaction patterns fast and cheaply. It let me pressure-test possibilities against the user\u2019s question before committing them to high-fidelity in Figma.',
        ],
      },
      { type: 'text',
        body: [
          'Handoff wasn\u2019t a file drop. I shared annotated screens and live documentation, then ran working sessions with engineering to walk through possible changes and improvements, marking each one as a clear, scoped note (change the colours, add a legend, add a tooltip) right on the design.',
        ],
      },
      { type: 'imageRow', cols: 2,
        images: [
          { src: 'assets/pharosgraph-govscape-dashboard.png', caption: 'GovScape, Lobbying Explorer, rebuilt in Figma', flush: true },
          { src: 'assets/pharosgraph-govscape-handoff.jpg', caption: 'Screens review, annotated handoff with scoped notes', flush: true },
        ],
      },
      { type: 'text', n: '05', title: 'Validating GovScape with real users',
        body: [
          'Before public launch I ran a moderated usability test of the core flows: five real target users, scenario-based tasks and a think-aloud protocol, scoring each task on completion, time, errors, help requests and an SEQ ease rating.',
          'I structured the study around four participant personas drawn from GovScape\u2019s customer base, and tagged every task to the persona it fits best, so each session could prioritise the tasks that matched the participant\u2019s real role.',
        ],
      },
      { type: 'principles', title: 'Four personas, tasks mapped to each',
        items: [
          { k: 'Lobbyist / Gov Affairs Strategist', v: 'Core user. Legislator profiling, constituent targeting and approach strategy. Lives in the briefing, profiles and lobbying data.' },
          { k: 'Public-Policy Analyst', v: 'Reads PolicyScape, bills and momentum to interpret where an issue is heading and why.' },
          { k: 'Advocacy / Grassroots Lead', v: 'Targets districts where constituents care, decoding Natural Fit scores and moral-foundations framing.' },
          { k: 'Corporate Gov Affairs', v: 'Generates testimony prep and stakeholder outreach, judging whether the tool produces trustworthy output.' },
        ],
      },
      { type: 'imageRow', cols: 2,
        images: [
          { src: 'assets/pharosgraph-usability-test-script.jpg', caption: 'Usability test script, study overview & personas', flush: true },
          { src: 'assets/pharosgraph-usability-test-task.jpg', caption: 'A scenario task with success criteria & post-task SEQ', flush: true },
        ],
      },
      { type: 'text', n: '06', title: 'A site built on the same system',
        body: [
          'The website was the first place the system had to prove it could leave the product and still hold.',
        ],
        bullets: [
          'Problem: the old site listed capabilities but did not carry the brand or explain, clearly, what a buyer would receive.',
          'Decision: redesign on the approved system, shaping the sections, the included materials, the images and the CTAs, with SEO built into the structure rather than added after.',
          'Result: a launched site that reads as one piece with the product. I ran the review and the developer handoff through to launch.',
        ],
      },
      { type: 'imageRow', cols: 2,
        images: [
          { src: 'assets/pharosgraph-website-lofi.jpg', caption: 'Website, lo-fi prototype', flush: true },
          { src: 'assets/pharosgraph-website-briefs.jpg', caption: 'Website briefs & case studies', flush: true },
        ],
      },
      { type: 'imageRow',
        images: [
          { src: 'assets/pharosgraph-website-mockup.png', caption: 'Launched site across tablet and mobile', flush: true },
        ],
      },
      { type: 'text',
        body: [
          'I reviewed the whole site end to end before launch, the SEO, every page, and all the imagery, checking each layout held up across desktop, tablet and mobile. Each fix went back to engineering as a clear, scoped note on top of the live screens.',
        ],
      },
      { type: 'imageRow',
        images: [
          { src: 'assets/pharosgraph-website-review-devices.jpg', caption: 'Pre-launch review across tablet and mobile, annotated', flush: true },
        ],
      },
      { type: 'text', n: '07', title: 'Where the system proved it scaled',
        body: [
          'A system is only real once other people can produce on it without breaking it. Content and go-to-market were that test.',
          'On content, I set the SEO foundation, with patterns for titles, meta descriptions and image alt text, and defined an illustration style for blog posts and press releases tied to the editorial and to the brand. I then created the imagery, covers and post styles for social across LinkedIn, BlueSky and Twitter.',
          'On go-to-market, I built the pattern for the full material set so the team could produce on-system and on-voice: one-pagers for the products, a business presentation deck and a pitch deck, plus case studies, intelligence briefs and proof sheets.',
        ],
      },
      { type: 'imageRow', cols: 2,
        images: [
          { src: 'assets/pharosgraph-social-linkedin.jpg', caption: 'Social, LinkedIn posts & covers', flush: true },
          { src: 'assets/pharosgraph-intelligence-brief.png', caption: 'Intelligence brief, on-system layout', flush: true },
        ],
      },
      { type: 'text',
        body: [
          'I also helped develop the visual style for blog and press-release imagery, moving from generic stock photography to original illustrations built on the PharosGraph design system. Using AI together with the system\u2019s palette and language, we produced a consistent, on-brand look, old version on the left, the new system-driven result on the right.',
        ],
      },
      { type: 'imageRow',
        images: [
          { src: 'assets/pharosgraph-blog-image-style.jpg', caption: 'Blog imagery, old stock photo vs new system-driven illustration', flush: true },
        ],
      },
      { type: 'kpis', n: '08', title: 'One language, from data to press release',
        body: 'The decision to fix the foundation first is what made the rest cohere. The same rules now run from the research board through the GovScape dashboard, the website and every published material.',
        kpis: [
          { label: 'Workstreams unified', value: '7 → 1', desc: 'From research to marketing, under one design system and voice.' },
          { label: 'Approach', value: 'Foundation first', desc: 'System rebuilt before the surfaces, so product, site and collateral stayed coherent by default.' },
          { label: 'Ownership', value: 'End to end', desc: 'Research, branding, design system, product, website and go-to-market.' },
        ],
        closing: 'Design stopped being a series of separate jobs and became one system the whole team builds on.',
      },
      { type: 'callout', kind: 'placeholder', title: 'Screens available on request',
        body: 'Dashboard, design system and collateral are anonymised for confidentiality. Happy to walk through the full work live.',
      },
    ],
    next: 'coke-ko-boss',
    prev: 'audi-onboarding',
  },

  /* ─────────────────────────────────────────────────────────────────────── */
  'coke-ko-boss': {
    n: '03',
    slug: 'coke-ko-boss',
    card: 'assets/coca-cola-ko-boss-cover.png', cardBg: '#2B2B2B',
    company: 'The Coca-Cola Company · KO Boss',
    year: '2024',
    title: 'A B2B buying tool for Coca-Cola bottlers',
    subtitle: 'Redesigning the bottler buying experience across five LATAM countries, design system, branding, and migrating Equipment Maintenance out of a WhatsApp bot into the app.',
    cover: '',
    meta: [
      { label: 'Role',     value: 'Product Designer' },
      { label: 'Timeline', value: '12 months' },
      { label: 'Team',     value: '26 people · me, managers, devs, business analysts' },
      { label: 'Method',   value: 'Lean UX + Agile' },
      { label: 'Markets',  value: 'Mexico, Paraguay, Chile, Argentina, Brazil' },
      { label: 'Tools',    value: 'Figma, Miro, Illustrator, Photoshop, Azure, Teams' },
    ],
    sections: [
      { type: 'text', n: '01', title: 'Context',
        body: [
          'Coca-Cola is the most recognised brand in the world, selling around 2 billion products daily.',
          'I developed a tool to facilitate the buying and selling process between bottlers and the distributor market, through web applications, chatbots and other communication systems.',
        ],
      },
      { type: 'kpis', n: '02', title: 'Results',
        kpis: [
          { label: 'Conversion',        value: '+6%',           desc: 'Lift in conversion rate post-launch' },
          { label: 'New features',      value: '23',            desc: 'Shipped during the engagement' },
          { label: 'Usability (SUS)',   value: '65 → 85',       desc: 'Poor → Excellent in post-launch testing' },
          { label: 'Discoverability',   value: '2.5 → 4.2',     desc: 'Rating improvement' },
          { label: 'Design system',     value: '5 countries',   desc: 'A single pattern across all bottlers' },
        ],
        closing: 'Over twelve months we lifted conversion by 6%, shipped 23 new features, and moved the System Usability Scale from a poor 65 to an excellent 85, backed by a design system that finally gave every bottler in five LATAM countries the same product to sell.',
      },
      { type: 'text', n: '03', title: 'Problem',
        bullets: [
          'High cart abandonment due to poor product discoverability',
          'Inconsistent experience across 5 countries',
          'Manual workarounds for routine tasks like equipment maintenance',
          'Low adoption, SUS score of 65',
        ],
      },
      { type: 'imageRow', n: '04', title: 'Design / strategic improvements', cols: 2,
        body: 'Old version vs new version, fixing contrast, spacing, branding consistency, product highlighting and search.',
        bullets: [
          'Modern visual design',
          'Contrast aligned to WCAG guidelines',
          'Branding and a logotype',
          'Design system to create a strong pattern across pages',
          'New search bar to find products easily',
          'Highlight for products + marketing discovery (story-style)',
          'Padding adjustment across all pages',
        ],
        images: [
          { src: 'assets/Old-version-e1769692000902-ridc1xmxn3874xaw7czg3ho8u01ysz7c6fg3x6ncsu.png', caption: 'Old version, audit', maxWidth: '80%' },
          { src: 'assets/Group-9377-qx09obrcuujojqv3ai0znvp0saknj1irze7wxb3s2s.jpg',                caption: 'New version', maxWidth: '80%' },
          { src: 'assets/Group-56-1024x601.jpg', caption: 'Side-by-side comparison', wide: true },
        ],
      },
      { type: 'imageRow', n: '05', title: 'Stakeholder map',
        body: 'Many stakeholders, managers, business analysts, developers and bottler owners. I mapped them to define communication channels and prioritise feedback loops, ensuring alignment across five distinct LATAM markets.',
        images: [
          { src: 'assets/Stakeholders-map-1024x649.jpg', caption: 'Stakeholder map' },
        ],
      },
      { type: 'callout', kind: 'leadership', title: 'Aligning 26 people across 5 countries',
        body: 'Owning the design across that span meant the harder craft was alignment, not pixels, running stakeholder reviews, prioritising feedback loops, and protecting one cohesive design language as five regional teams pulled in different directions.',
      },
      { type: 'imageRow', n: '06', title: 'UX scorecard analysis', cols: 2,
        body: 'A scorecard combining the System Usability Scale (SUS) with the Technology Acceptance Model (TAM), measuring Discoverability (how easily users find, access and authenticate), Usability (how intuitively they navigate), and Desirability (whether they return).',
        images: [
          { src: 'assets/UX-scorecard-analysis-Disoverability-1024x737.jpg',  caption: 'Discoverability scorecard' },
          { src: 'assets/UX-scorecard-analysis-Disoverability-1-1024x737.jpg', caption: 'Usability scorecard' },
          { src: 'assets/UX-scorecard-analysis-Disoverability-2-1024x709.jpg', caption: 'Desirability scorecard', wide: true },
        ],
      },
      { type: 'imageRow', n: '07', title: 'Competitive analysis', cols: 2,
        body: 'Direct competitors, Zé Delivery, Heineken app, Bees Ambev. Indirect, iFood, Uber Eats. Items analysed: onboarding, menu exploring, search, user flows, promotions, tone of voice, reviews.',
        images: [
          { src: 'assets/What-is-Ze-Delivery.jpg',          caption: 'Zé Delivery, overview' },
          { src: 'assets/Tone-of-voice-My-Heineken.jpg',    caption: 'Heineken, tone of voice' },
          { src: 'assets/Searching-for-products-Bees-Ambev.jpg', caption: 'Bees Ambev, search' },
          { src: 'assets/Menu-exploring-Bees-Ambev.jpg',    caption: 'Bees Ambev, menu' },
        ],
      },
      { type: 'callout', kind: 'leadership', noTag: true, title: 'From analysis to a shared roadmap',
        body: 'After the competitive analysis I built this board to translate findings into clear, actionable tasks for the roadmap. I discussed every item with the managers, checking that each one was linked to our OKRs before it made the cut, so the roadmap stopped being a list of features and started being a contract with the business.',
      },
      { type: 'imageRow',
        images: [
          { src: 'assets/Strategy-1-1024x910.jpg',          caption: 'Feature opportunities synthesised', wide: true },
        ],
      },
      { type: 'imageRow', n: '08', title: 'Design system', cols: 2,
        body: 'To ensure scalability across five countries, I authored a comprehensive design system that standardised the component library, the contribution model, and the seniority rubric the team still uses today.',
        images: [
          { src: 'assets/0.-Cover.jpg',                 caption: 'DS, cover' },
          { src: 'assets/1.-Table-of-contents.jpg',    caption: 'Table of contents' },
          { src: 'assets/3.-Design-principles.jpg',    caption: 'Design principles' },
          { src: 'assets/5.-Colors-scaled.jpg',        caption: 'Colour tokens' },
          { src: 'assets/6.-Elevation.jpg',            caption: 'Elevation system' },
          { src: 'assets/7.-Spacing.jpg',              caption: 'Spacing scale' },
          { src: 'assets/10.-General-icons.jpg',       caption: 'General icons' },
          { src: 'assets/8.-Responsive-design-scaled.jpg', caption: 'Responsive grid' },
          { src: 'assets/17.-Product-cards-scaled.jpg',caption: 'Product cards' },
          { src: 'assets/16.-Buttons-scaled.jpg',      caption: 'Buttons' },
          { src: 'assets/20.-Dropdown.jpg',            caption: 'Dropdowns' },
          { src: 'assets/21.-Text-inputs.jpg',         caption: 'Text inputs' },
        ],
      },
      { type: 'callout', kind: 'leadership', title: 'One pattern across every channel',
        body: 'The design system wasn\u2019t just for the bottler app, the same tokens, components and voice extended into the marketing landing pages, the onboarding decks, the WhatsApp comms and the internal docs. By the end of the engagement, no matter where a bottler met Coca-Cola digitally, they saw the same product.',
      },
      { type: 'imageRow', n: '09', title: 'Task · Equipment maintenance',
        body: 'After discovery, I migrated the Equipment Maintenance feature from a WhatsApp bot (Solar BR) into the Latam Shopping Cart app, analysing the original flow, sketching on paper, building lo-fi prototypes for team review, then hi-fi with developer notes.',
        images: [
          { src: 'assets/Equipment-1-1024x312.jpg',        caption: 'Original WhatsApp flow' },
          { src: 'assets/1_services_flow.jpg',             caption: 'New app-native flow' },
        ],
      },
      { type: 'imageRow',
        images: [
          { src: 'assets/Captura-de-Tela-2024-06-28-as-15.29.48-1024x577.png', caption: 'Lo-fi prototype' },
        ],
      },
      { type: 'imageRow', cols: 3,
        images: [
          { src: 'assets/Group-51.jpg',                    caption: 'Hi-fi, step 1' },
          { src: 'assets/Group-52.jpg',                    caption: 'Hi-fi, step 2' },
          { src: 'assets/Group-53.jpg',                    caption: 'Hi-fi, step 3' },
        ],
      },
      { type: 'text', n: '10', title: 'All delivered tasks',
        bullets: [
          'Promotions section',
          'Suggested order page',
          'Maximum amount in the cart',
          'New colour palette for the system',
          'Design system',
          'Branding & naming',
          'Erase product option',
          'Maintain quantity after adding to cart',
          'Product package info in the system',
          'Boleto as payment method',
          'Clear-cart button UX fix on mobile',
          'Filter and search in the app',
          'Equipment Maintenance on Latam Shopping',
        ],
      },
    ],
    next: 'ladle-slag-model',
    prev: 'pharosgraph',
  },

  /* ─────────────────────────────────────────────────────────────────────── */
  'ladle-slag-model': {
    n: '04',
    slug: 'ladle-slag-model',
    card: 'assets/rhi-magnesita-ladle-slag-model-cover.jpg', cardBg: '#333333',
    company: 'RHI Magnesita · Ladle Slag Model',
    year: '2024',
    title: 'Ladle Slag Model, digitising metallurgical expertise',
    subtitle: 'Leading the end-to-end design of an industrial SaaS for steel-plant operators across Austria and Brazil, from stakeholder research and business logic to UI, branding, design system and go-to-market.',
    cover: 'assets/rhi-magnesita-ladle-slag-model-cover.jpg',
    coverBg: '#333333',
    heroGallery: [
      'assets/rhi-hero-1-coffee.jpg',
      'assets/rhi-hero-2-team.jpg',
      'assets/rhi-hero-3-wall.jpg',
    ],
    heroGalleryAlt: [
      'A coffee cup carrying the Ladle Slag Model brand mark',
      'The cross-functional CI&T and RHI Magnesita project team',
      'RHI Magnesita signage on an office wall',
    ],
    coverAlt: 'RHI Magnesita Ladle Slag Model running on a laptop, showing the Tapping Mode monitoring interface',
    meta: [
      { label: 'Role',     value: 'Product Designer (lead)' },
      { label: 'Timeline', value: '12 months' },
      { label: 'Team',     value: '12 people · me, scrum master, squad leader, senior manager, 2 devs, QA, lead architect, technical marketing, 2 APO & AI experts, head of digital solutions' },
      { label: 'Method',   value: 'Lean UX + Scrumban' },
      { label: 'Markets',  value: 'Austria & Brazil' },
      { label: 'Tools',    value: 'Figma, Miro, Illustrator, Photoshop, Azure DevOps, Teams' },
    ],
    sections: [
      { type: 'text', n: '01', title: 'Context',
        body: [
          'At RHI Magnesita, a global leader in refractories operating at 1200°C+, I led the end-to-end design of the Ladle Slag Model.',
          'As the Product Designer I connected the gap between complex industrial automation and user-centric software, driving everything from initial stakeholder research and business logic to UI, branding and go-to-market strategy.',
        ],
      },
      { type: 'imageRow', n: '02', title: 'Discovery', cols: 2,
        body: 'A focused discovery to align the product team on value proposition, life-cycle stage, stakeholder landscape and the right way of working with engineering.',
        images: [
          { src: 'assets/Group-230-rit0m39u5n0hz0ytk9kympeqj0ebob652a36sbpy0u.jpg', caption: 'Value proposition' },
          { src: 'assets/Group-223-768x568.jpg',                                                  caption: 'Product life-cycle, mapped to the validation phase' },
          { src: 'assets/Group-248-rit0xjx1xm93unybseblp9asm5fbb65djmo0pomnzw.jpg', caption: 'Stakeholders map' },
          { src: 'assets/Group-249-rit131b5strbkrzlrrn98vhld2ee7lx0arnzhshz4e.jpg', caption: 'Agile-hybrid work model' },
        ],
      },
      { type: 'imageRow', n: '03', title: 'How the system operates',
        body: 'The Ladle Slag Model (LSM) digitises metallurgical expertise by translating real-time process data into precise chemical adjustment recommendations. A secure, API-driven workflow optimises slag saturation across two critical phases: Tapping and Ladle Furnace, ensuring operational efficiency from the automation system directly to the user\u2019s device.',
        images: [
          { src: 'assets/Group-310-rit19enpooxjyt3keueszbld03h3m0qfxonscf5fho.jpg', caption: 'End-to-end system flow', maxWidth: '80%' },
        ],
      },
      { type: 'imageRow', n: '04', title: 'Heuristic analysis', cols: 2,
        body: 'A heuristic analysis to identify and prioritise improvements, scoring each fix by severity and implementation difficulty. The output was a clear presentation enabling streamlined, actionable discussion with stakeholders.',
        images: [
          { src: 'assets/Captura-de-Tela-2023-03-01-as-15.58-1.jpg', caption: 'Heuristic findings, sheet 1', wide: true },
          { src: 'assets/Captura-de-Tela-2023-03-01-as-15.58.jpg',   caption: 'Heuristic findings, sheet 2', wide: true },
          { src: 'assets/Captura-de-Tela-2023-03-01-as-16.00.jpg',   caption: 'Severity / difficulty matrix', wide: true },
        ],
      },
      { type: 'callout', kind: 'leadership', title: 'From heuristic findings to a prioritised roadmap',
        body: 'After the heuristic analysis, I scored each fix against severity and implementation difficulty, then ran the matrix with the senior manager, the lead architect and the APO experts. We prioritised together, mapping every item back to the OKRs we needed to hit, so the heuristic stopped being a designer\u2019s opinion and became the team\u2019s shared roadmap.',
      },
      { type: 'imageRow', n: '05', title: 'Improvements, old vs new',
        body: 'Critical usability gaps mapped from the heuristic evaluation, translated into a design proposal that streamlines the metallurgical workflow.',
        images: [
          { src: 'assets/Group-311-rit271c0aku73mc8fknu3p4tduizxifebodv311lse.png', caption: 'Old version', note: 'Dated style, low contrast, no clear branding, redundant boxes, inconsistent patterns, required fields unflagged, no responsive mode.' },
          { src: 'assets/Group-312-rit2h37vdsll9hqkqf379nta36zb8zc21fjsuk518u.png', caption: 'New version', note: 'Modern visual language, WCAG-compliant contrast, branding and logotype, clean boxes only when needed, design system across pages, flagged required fields, responsive + collapsed menu.' },
        ],
      },
      { type: 'callout', kind: 'leadership', noTag: true, title: 'On-site at the meltshop',
        body: 'Beyond the screen work, I ran in-person plant visits to observe the meltshop environment first-hand, then facilitated cross-functional design workshops with engineers and operators, bridging technical constraints with the actual job people do at the line.',
      },
      { type: 'imageRow', n: '06', title: 'Design workshops',
        body: 'Collaborative sessions with engineers and operators to ideate solutions, map complex user flows and critique proposals. Every screen was reviewed and validated before development.',
        images: [
          { src: 'assets/20220719_153258-1024x720.jpg', caption: 'In-person workshop' },
          { src: 'assets/image-1-1024x471.jpg',         caption: 'Whiteboard flow' },
          { src: 'assets/Captura-de-Tela-2022-07-21-as-11.24.39-1024x351.png', caption: 'Workshop synthesis' },
          { src: 'assets/image-2-1024x474.jpg',         caption: 'Reviewed proposal' },
        ],
      },
      { type: 'imageRow', n: '07', title: 'Branding', cols: 2,
        body: 'Testing with engineers showed the tool lacked a cohesive identity, relying on generic typography that failed to reflect its technical power. I built a brand identity rooted in persona research, aligning the visual language with the business model, turning a utility into a market-ready product.',
        images: [
          { src: 'assets/1-Cover.jpg',                       caption: 'Cover' },
          { src: 'assets/2-Branding-Ladle-Slag-Model.jpg',   caption: 'Brand foundations' },
          { src: 'assets/3-Positioning.jpg',                 caption: 'Positioning' },
          { src: 'assets/4-Personas.jpg',                    caption: 'Personas' },
          { src: 'assets/5-Archetype.jpg',                   caption: 'Archetype' },
          { src: 'assets/6-Brand-attributes.jpg',            caption: 'Brand attributes' },
          { src: 'assets/7-Brand-voice.jpg',                 caption: 'Brand voice' },
          { src: 'assets/8-Tagline.jpg',                     caption: 'Tagline' },
          { src: 'assets/9-Logo-concept.jpg',                caption: 'Logo concept' },
          { src: 'assets/10-Logotype.jpg',                   caption: 'Logotype' },
        ],
      },
      { type: 'imageRow', n: '08', title: 'Design system', cols: 2,
        body: 'After the brand rollout I architected a comprehensive design system, a library of standardised patterns and reusable components that ensured visual consistency and accelerated the development cycle for both legacy screens and new feature sets.',
        images: [
          { src: 'assets/1-Cover-1-1024x667.jpg',      caption: 'Cover' },
          { src: 'assets/2-About-1024x611.jpg',        caption: 'About' },
          { src: 'assets/5-Tipography-803x1024.jpg',   caption: 'Typography' },
          { src: 'assets/4-Color-724x1024.jpg',        caption: 'Colour tokens' },
          { src: 'assets/20-Search-974x1024.png',      caption: 'Search' },
          { src: 'assets/15-Table-1024x1024.png',      caption: 'Tables' },
          { src: 'assets/18-Radio-button-814x1024.jpg',caption: 'Radio buttons' },
          { src: 'assets/12-Button-1024x930.jpg',      caption: 'Buttons' },
        ],
      },
      { type: 'callout', kind: 'leadership', title: 'One pattern across every channel',
        body: 'The brand and design system extended beyond the product into landing pages, video, email and WhatsApp comms. I owned the broader product view so an engineer reviewing the LSM app, a buyer reading a launch email, and a stakeholder watching the demo video all met the same Ladle Slag Model.',
      },
      { type: 'imageRow', n: '09', title: 'Marketing materials', cols: 2,
        body: 'To support product launch and adoption I designed a multichannel asset suite: high-conversion landing pages, a video presentation, strategic email campaigns and targeted WhatsApp communications, ensuring a consistent brand experience across every touchpoint.',
        images: [
          { src: 'assets/Group-313-768x2305.png',                  caption: 'Landing page', narrow: true },
          { src: 'assets/Newsletter-2-New-user-LSM-Proposal.jpg',  caption: 'Email marketing' },
        ],
      },
      { type: 'imageRow', n: '10', title: 'Feature engineering, 17+ modules', cols: 2,
        body: 'Designed and delivered 17 complex technical features, including Tapping Mode, Steel Grade & Category Management, Plating User Administration and Draft Editing Restrictions, each meeting rigorous engineering requirements.',
        images: [
          { src: 'assets/Quick-wins-New-column-Na2O-e-K2O-Opened-1024x717.jpg',           caption: 'Quick wins, new columns' },
          { src: 'assets/01.-Draft-heats-Prototype-Current-design-and-rules-1024x709.jpg', caption: 'Draft heats prototype' },
          { src: 'assets/07.-Change-inference-Message-Part-2-1024x717.jpg',                caption: 'Change inference message', wide: true },
        ],
      },
      { type: 'text', n: '11', title: 'Key contributions & impact',
        bullets: [
          'Product redesign with WCAG-compliant contrast and accessibility, simplifying flows to reduce cognitive load in high-pressure environments.',
          'Branding and design system architected from the ground up, unifying patterns across the platform and accelerating new component delivery.',
          'On-site field research at the meltshop, observing operators in context and bridging technical constraints with user needs.',
          'Feature engineering across 17+ technical modules meeting rigorous metallurgical and engineering requirements.',
        ],
      },
    ],
    next: 'sales-tech-ecosystem',
    prev: 'coke-ko-boss',
  },

  /* ─────────────────────────────────────────────────────────────────────── */
  'sales-tech-ecosystem': {
    n: '05',
    slug: 'sales-tech-ecosystem',
    card: 'assets/kraft-heinz-sales-tech-ecosystem-cover.jpg', cardBg: '#C9252A',
    company: 'Kraft Heinz · Sales Tech',
    year: '2023',
    title: 'A sales-tech ecosystem for Kraft Heinz',
    subtitle: 'Leading the design of the Sales Tech Ecosystem for Kraft Heinz, a key initiative in the company\u2019s digital transformation. Sell-In, Execution and Sell-Out unified into one source of truth, across France and Brazil.',
    cover: '',
    meta: [
      { label: 'Role',     value: 'Product Designer (lead)' },
      { label: 'Timeline', value: '12 months' },
      { label: 'Team',     value: '17 people · me, managers, devs, business analysts' },
      { label: 'Method',   value: 'Scrum, bi-weekly sprints' },
      { label: 'Markets',  value: 'France & Brazil' },
      { label: 'Tools',    value: 'Figma, Miro, Illustrator, Photoshop, Jira' },
    ],
    sections: [
      { type: 'text', n: '01', title: 'Context',
        body: [
          'I led the design of the Sales Ecosystem for Kraft Heinz, a key initiative in the company\u2019s digital transformation. Focusing on Sell-In, Execution and Sell-Out processes, I translated user insights into a unified, flawless experience for global brands.',
          'My role spanned the full lifecycle, from initial discovery to prototyping, testing and final assessment.',
        ],
      },
      { type: 'imageRow', n: '02', title: 'The problem',
        body: 'Sales teams relied on fragmented, static spreadsheets to track key performance indicators, leading to reactive decision-making and missed forecast targets.',
        images: [
          { src: 'assets/Map-768x351.jpg', caption: 'Markets, France and Brazil', maxWidth: '70%' },
        ],
      },
      { type: 'imageRow', n: '03', title: 'Solution, from spreadsheets to a single source of truth', cols: 2,
        body: 'The goal was to concentrate the most important information so the sales team could get insights quickly and easily. The final result was a suite of dashboards unifying sales operations and enabling predictive strategic planning.',
        images: [
          { src: 'assets/Old-768x446.jpg',  caption: 'Old version, fragmented spreadsheets', note: 'Inaccurate, error prone, complex usability.' },
          { src: 'assets/New-768x446.jpg',  caption: 'New version, unified dashboard', note: 'Automatic, data validated, easy to use.' },
        ],
      },
      { type: 'imageRow', cols: 2,
        images: [
          { src: 'assets/Group-30.jpg',     caption: 'Suite of dashboards' },
          { src: 'assets/Group-28.jpg',     caption: 'Cross-dashboard flow' },
        ],
      },
      { type: 'imageRow', n: '04', title: 'OKRs and approach', cols: 2,
        body: 'The OKR framework bridged high-level vision with tactical execution, giving the team clear, measurable goals and a shared sense of focus.',
        images: [
          { src: 'assets/ORKs-1-300x94.jpg',     caption: 'OKRs' },
          { src: 'assets/Approach-300x269.jpg', caption: 'Approach' },
          { src: 'assets/Operations-1024x700.jpg', caption: 'Operations cadence', wide: true },
        ],
      },
      { type: 'imageRow', n: '05', title: 'System map & architecture', cols: 2,
        body: 'A modular architecture balancing specialised business solutions with foundational data systems, organised across three core verticals: Sell In, Sell Out and Execution. Deep-level data integration from SAP, Involves and Nielsen ensured a single, cohesive source of truth.',
        images: [
          { src: 'assets/System-768x529.jpg',          caption: 'System map' },
          { src: 'assets/Team-768x444.jpg',            caption: 'Team and stakeholders' },
          { src: 'assets/Architecture-768x401.jpg',    caption: 'Architecture across Sell-In, Sell-Out, Execution' },
          { src: 'assets/System_Evolve-768x220.jpg',   caption: 'Roll-out plan, France and Brazil first' },
        ],
      },
      { type: 'callout', kind: 'leadership', title: 'Cross-functional workshops as the unlock',
        body: 'My approach to dashboard creation is rooted in cross-functional workshops. I bridge the gap between business needs and data reality by sketching solutions with the end-users and validating data opportunities with the analytics team in real time, compressing the discovery phase and building shared vision instantly.',
      },
      { type: 'imageRow', n: '06', title: 'Discovery sessions',
        body: 'Focused sessions where business needs meet data reality, sketching live with end-users and validating data opportunities with the analytics team in real time.',
        images: [
          { src: 'assets/mural-768x1044.png', caption: 'Discovery mural' },
        ],
      },
      { type: 'imageRow', n: '07', title: 'Exploring prototypes', cols: 2,
        body: 'With constraints defined, I moved into rapid ideation, paper sketches to explore multiple dashboard layouts, then low-fidelity prototypes to validate flow and structural feasibility before high-fidelity.',
        images: [
          { src: 'assets/execution-skecth-768x432.jpg',     caption: 'Execution dashboard sketch' },
          { src: 'assets/Execution-x-Sell-Out-768x440.jpg', caption: 'Execution × Sell-Out lo-fi' },
        ],
      },
      { type: 'imageRow', n: '08', title: 'Branding', cols: 2,
        body: 'A brand system to keep the pattern consistent across designs and to create lasting value for stakeholders.',
        images: [
          { src: 'assets/1-Cover-1024x665.jpg',                          caption: 'Cover' },
          { src: 'assets/2-Branding-Sale-Tech-Ecosystem-1024x665.jpg',   caption: 'Brand foundations' },
          { src: 'assets/6-Purpose-1024x665.jpg',                        caption: 'Purpose' },
          { src: 'assets/7-Mission-1024x665.jpg',                        caption: 'Mission' },
          { src: 'assets/8-Vision-1024x665.jpg',                         caption: 'Vision' },
          { src: 'assets/9-Attributes-1024x665.jpg',                     caption: 'Attributes' },
          { src: 'assets/10-Brand-prism-1024x665.jpg',                   caption: 'Brand prism' },
          { src: 'assets/11-Positioning-1024x665.jpg',                   caption: 'Positioning' },
          { src: 'assets/12-Tagline-1024x665.jpg',                       caption: 'Tagline' },
          { src: 'assets/14-Logo-construction-1024x665.jpg',             caption: 'Logo construction' },
          { src: 'assets/15-Logo-applications-1024x665.jpg',             caption: 'Logo applications' },
          { src: 'assets/16-Logo-variants-1024x665.jpg',                 caption: 'Logo variants' },
          { src: 'assets/17-Color-1024x665.jpg',                         caption: 'Colour' },
          { src: 'assets/18-Typography-1024x665.jpg',                    caption: 'Typography' },
          { src: 'assets/19-Brand-voice-1024x665.jpg',                   caption: 'Brand voice' },
          { src: 'assets/22-Iconography-1024x665.jpg',                   caption: 'Iconography' },
          { src: 'assets/26-Presentation-deck-template-1024x665.jpg',    caption: 'Presentation deck' },
          { src: 'assets/28-Dashboard-guidelines-1024x665.jpg',          caption: 'Dashboard guidelines' },
        ],
      },
      { type: 'imageRow', n: '09', title: 'Style guide for dashboards', cols: 2,
        body: 'A style guide to keep the design standards consistent across dashboards and communications.',
        images: [
          { src: 'assets/Cover-1024x665.jpg',         caption: 'Cover' },
          { src: 'assets/Color-1024x665.jpg',         caption: 'Colour' },
          { src: 'assets/Typography-1024x665.jpg',    caption: 'Typography' },
          { src: 'assets/Spacing-1024x665.jpg',       caption: 'Spacing' },
          { src: 'assets/Buttons-1024x665.jpg',       caption: 'Buttons' },
          { src: 'assets/Dropdowns-1024x665.jpg',     caption: 'Dropdowns' },
          { src: 'assets/Cards-1024x665.jpg',         caption: 'Cards' },
          { src: 'assets/Tables-1024x665.jpg',        caption: 'Tables' },
          { src: 'assets/Navigation-1024x665.jpg',    caption: 'Navigation' },
          { src: 'assets/Icons-1024x665.jpg',         caption: 'Icons' },
          { src: 'assets/Text-fields-1024x665.jpg',   caption: 'Text fields' },
          { src: 'assets/Tips-1024x665.jpg',          caption: 'Tips' },
        ],
      },
      { type: 'text', n: '10', title: 'Design principles for all dashboards',
        bullets: [
          '5-second rule, critical insights visible within 5 seconds.',
          'Exception-based design, red / yellow / green draws attention to action items.',
          'Progressive disclosure, summary first, drill-down available.',
        ],
      },
      { type: 'imageRow', n: '11', title: 'Run Rate',
        body: 'Sales managers struggled to identify performance trends quickly. The dashboard compares the current month against multiple time windows to reveal both short-term momentum and long-term trends, multi-timeframe comparison, percentage changes over raw numbers, category-level breakdown.',
        images: [
          { src: 'assets/Run-rate.jpg', caption: 'Run Rate dashboard' },
        ],
      },
      { type: 'imageRow', n: '12', title: 'Joint Value Plan',
        body: 'Account managers manually analysed hundreds of clients to decide where to invest. A 2×2 matrix segments customers by Attractiveness (market potential) and Ability to Win (competitive position), with bubble size for revenue opportunity, instant strategic picture across NSV, CMA% and Market Share%.',
        images: [
          { src: 'assets/Jarvis.jpg', caption: 'Joint Value Plan' },
        ],
      },
      { type: 'imageRow', n: '13', title: 'Daily Sales',
        body: 'Sales reps only knew if they were on track at month-end. Daily tracking of volume against monthly commitments (CMT) and annual targets (AOP), with three-tier client classification (Under / OK / Over) enabling early course-correction.',
        images: [
          { src: 'assets/Daily-sales.jpg', caption: 'Daily Sales' },
        ],
      },
      { type: 'imageRow', n: '14', title: 'Execution & Retail Operations',
        body: 'Field teams tracked in-store execution (pricing, shelf, merchandising) separately from sales outcomes. A unified view tracks five execution drivers with their direct correlation to sell-out performance over time, cause-and-effect made visible in one synchronised timeline.',
        images: [
          { src: 'assets/Execution.jpg', caption: 'Execution & Retail Operations' },
        ],
      },
      { type: 'imageRow', n: '15', title: 'Order Analysis',
        body: 'Unfulfilled orders were getting lost in spreadsheets, causing stock-outs at key retailers. An age-based classification system shows fulfilment status across a matrix of clients and products, with visual colour-coding for priority and interactive filtering.',
        images: [
          { src: 'assets/Oder-analysis.jpg', caption: 'Order Analysis' },
        ],
      },
      { type: 'imageRow', n: '16', title: 'Perfect Store',
        body: 'Store auditors collected execution scores but regional managers couldn\u2019t identify which locations or states needed support. Dual geographic visualisation at state and city levels, combined with monthly trend tracking by performance tier (G / P / M / R).',
        images: [
          { src: 'assets/Perfect-store.jpg', caption: 'Perfect Store' },
        ],
      },
      { type: 'imageRow', n: '17', title: 'Sell-In vs Sell-Out',
        body: 'Pricing managers couldn\u2019t see the relationship between the price Kraft Heinz charged retailers (sell-in) and the price retailers charged consumers (sell-out). A dual-line chart with per-KG standardisation and gap calculation quantifies margin opportunity or risk.',
        images: [
          { src: 'assets/Sell-in-vs-sell-out.jpg', caption: 'Sell-In vs Sell-Out' },
        ],
      },
      { type: 'imageRow', n: '18', title: 'Commercial & Pricing',
        body: 'Analysts spent days manually pulling retailer data into Excel. A flexible comparison tool lets users select any two KPIs and instantly visualise their relationship over any time period, dual-line graph with independent scales, dynamic time-period selection.',
        images: [
          { src: 'assets/Sell-Out-2nd-Party-Data.jpg', caption: 'Commercial & Pricing' },
        ],
      },
      { type: 'imageRow', n: '19', title: 'Sell Out',
        body: 'Category managers needed to understand how Kraft Heinz products were performing at retail but lacked visibility into the drivers. A grid layout shows eight key retail KPIs with year-over-year comparison, plus trend visualisation for the selected metric.',
        images: [
          { src: 'assets/Sell-out.jpg', caption: 'Sell Out' },
        ],
      },
      { type: 'imageRow', n: '20', title: 'Newsletter',
        body: 'A weekly newsletter to share new dashboards, roadmap status and other highlights, keeping the sales organisation tuned in to the evolving product.',
        images: [
          { src: 'assets/Newsletter-1-VS2-Proposal-1-217x1024.jpg', caption: 'Weekly newsletter', narrow: true },
        ],
      },
      { type: 'kpis', n: '21', title: 'Results',
        kpis: [
          { label: 'Time to insight',     value: '20h → 2s',     desc: '36,000× faster, from monthly spreadsheet pulls to one-click dashboards' },
          { label: 'Dashboards shipped',  value: '9',            desc: 'Run Rate, JVP, Daily Sales, Execution, Order Analysis, Perfect Store, Sell-In vs Sell-Out, Commercial, Sell Out' },
          { label: 'Markets live',        value: 'France · Brazil', desc: 'With a roll-out plan across the rest of Kraft Heinz operations' },
        ],
      },
    ],
    next: 'audi-onboarding',
    prev: 'ladle-slag-model',
  },

};

Object.assign(window, { CASES });
